name: mcpc
run-name: mcpc
on: [push]
jobs:
  x64-linux-gcc10-glibc231:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l .
      - run: sudo apt-get install -y buildah podman
      - run: buildah from --name wctn docker.io/library/debian:bullseye
      - run: buildah run wctn -- apt-get update
      - run: buildah run wctn -- apt-get install -y sudo bash gcc make
      - run: buildah copy wctn ../mcpc /mcpc
      - run: buildah run wctn -- bash -c "cd /mcpc && CC=gcc make tst"
      - run: buildah run wctn -- bash -c "cd /mcpc && CC=gcc make install"
      - run: buildah run wctn -- bash -c "ls -l /usr/local/lib"
  x64-linux-gcc12-glibc236:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l .
      - run: sudo apt-get install -y buildah podman
      - run: buildah from --name wctn docker.io/library/debian:bookworm
      - run: buildah run wctn -- apt-get update
      - run: buildah run wctn -- apt-get install -y sudo bash gcc make
      - run: buildah copy wctn ../mcpc /mcpc
      - run: buildah run wctn -- bash -c "cd /mcpc && CC=gcc make tst"
      - run: buildah run wctn -- bash -c "cd /mcpc && CC=gcc make install"
      - run: buildah run wctn -- bash -c "ls -l /usr/local/lib"
  x64-linux-gcc14-glibc240:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l .
      - run: sudo apt-get install -y buildah podman
      - run: buildah from --name wctn docker.io/library/fedora:41
      - run: buildah run wctn -- dnf install -y bash gcc make
      - run: buildah copy wctn ../mcpc /mcpc
      - run: buildah run wctn -- bash -c "cd /mcpc && CC=gcc make tst"
      - run: buildah run wctn -- bash -c "cd /mcpc && CC=gcc make install"
      - run: buildah run wctn -- bash -c "ls -l /usr/local/lib"
  x64-win2022-vs2022:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - shell: cmd
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&  dir' }}
      - shell: cmd
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&  make' }}
      - shell: cmd
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&  make tst' }}
      - run: dir tst/itst-svcalc.exe
      - run: ldd tst/itst-svcalc.exe
  x64-win2025-vs2022:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - shell: cmd
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&  dir' }}
      - shell: cmd
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&  make' }}
      - shell: cmd
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&  make tst' }}
      - run: dir tst/itst-svcalc.exe
      - run: ldd tst/itst-svcalc.exe
  x64-win2022-gcc:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: gcc --version
      - run: make --version
      - run: make tst
      - run: ldd tst/itst-svcalc.out
  x64-win2025-gcc:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - run: gcc --version
      - run: make --version
      - run: make tst
      - run: ldd tst/itst-svcalc.out
  x64-mac13-clang:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: make tst
      - run: otool -L tst/itst-svcalc.out
  x64-mac14-clang:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: make tst
      - run: otool -L tst/itst-svcalc.out
  x64-mac15-clang:
    if: contains(github.event.head_commit.message, 'NO_GH_CI') == false
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: make tst
      - run: otool -L tst/itst-svcalc.out


